### ISSUE TITLE
Unicode char be \uxxxx,How to fix it

### ISSUE THREAD

**Issue by chanble** [json-emacs/json-mode#38]
When I beautify buffer with Chinese,  the Chinese char be \uxxxx.
I use ubuntu, emacs 24.5.1

**Comment by Thomsen** [comment]
@chanble  +1

**Comment by davidshen84** [comment]
It seems [json-reformat][1] can support encoding/decoding. But *json-mode* did not pass the correct arguments to it.

[1]: https://github.com/gongo/json-reformat

**Comment by hanzhixing** [comment]
@chanble +1
