### ISSUE TITLE
Indent automatically when using electric-pair-mode

### ISSUE THREAD

**Issue by raxod502** [json-emacs/json-mode#50]
In js2-mode, with electric-pair-mode enabled, and point `|` positioned as follows:

```
{|}
```

I can press `RET` to get the following:

```
{
    |
}
```

Unfortunately, doing the same in json-mode only gives:

```
{
|}
```

I think this may have something to do with the syntax table (not) provided by json-mode, since both js2-mode and json-mode inherit from js-mode.

**Comment by taku0** [comment]
It works now.
