### ISSUE TITLE
Should I try to implement my features for this mode?

### ISSUE THREAD

**Issue by UwUnyaa** [json-emacs/json-mode#63]
I've received an issue on my custom JSON mode asking for it to be published on MELPA (https://github.com/UwUnyaa/json-mode/issues/4). Since this mode provides pretty similar functionality, my best bet is to try to add functionality into this mode, as MELPA doesn't like duplicates.

The features I'd consider adding are:
- folding support
- optional support for alternative JSON path formats
- optional key to minify JSON

Should I try to make a push request? This project doesn't seem to be that active, so I'm not sure whether anyone would even bother taking a look at my PR.

**Comment by taku0** [comment]
Feel free to make a PR, or even becoming a member of the organization.
