### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by UwUnyaa** [json-emacs/json-mode#64]
I'd like to know whether this repository is being maintained as of now, or whether the maintainer has moved onto something else.

**Comment by kahironimashte** [comment]
@UwUnyaa If it is not dead, I would vote for merging some features of your project with the same name, like folding, into this one :+1:

**Comment by UwUnyaa** [comment]
In that case, I'll put making a PR to your project on my todo list, expect it in near future.

**Comment by taku0** [comment]
I got the repository transferred to me, and I set up an organization. Please feel free to make a PR.
