### ISSUE TITLE
C-c P is not a well-defined mode-specific keybinding

### ISSUE THREAD

**Issue by UwUnyaa** [json-emacs/json-mode#66]
https://github.com/joshwnj/json-mode/blob/0e819e519ae17a2686e0881c4ca51fa873fa9b83/json-mode.el#L140

This command is bound to `C-c P`, which is a `C-c letter` keybinding, reserved for user customization. It should be replaced with some other binding, such as `C-c C-w`, which doesn't seem to be used by the parent mode. I can submit a patch, but deciding on what keybinding makes sense first is the more productive way to accomplish this.

**Comment by UwUnyaa** [comment]
I forgot to link the relevant section of the elisp manual: https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html#Key-Binding-Conventions

**Comment by taku0** [comment]
Fixed via #70.
