### ISSUE TITLE
Newline indent level

### ISSUE THREAD

**Issue by danepowell** [json-emacs/json-mode#75]
It seems like there's no way to set the newline indent level. If you have a JSON file indented at 4 spaces (as is the standard for composer.json, for instance) and add a newline anywhere in the file, the line gets reformatted to 2 spaces.

`js-indent-level` has no effect. My understanding is that `json-reformat:indent-level` only affects the reformat level, not when adding a newline, and anyway support for json-reformat was removed in #69.

**Comment by taku0** [comment]
Does `js-indent-level` still not work?  It works on my machine.  I have updated README. https://github.com/json-emacs/json-mode/commit/8487a1ac7b17f63f892dd292c4cd01d0004a8886
