### ISSUE TITLE
Incorrect indentation for arrays of objects

### ISSUE THREAD

**Issue by galdor** [json-emacs/json-mode#77]
Indentation is incorrect for arrays of objects:

```json
[
  {
  "a": 1
}
]
```

Expected:
```json
[
  {
    "a": 1
  }
]
```

**Comment by taku0** [comment]
This was fixed (https://github.com/json-emacs/json-mode/issues/72) but not released as a package.
I have just released v1.9.0.  Could you try it? You can try it from https://github.com/json-emacs/json-mode/releases/tag/v1.9.0 or Melpa.

**Comment by galdor** [comment]
This is indeed working properly on v1.9.0, thank you!
