### ISSUE TITLE
No highlighting for jsonc-mode

### ISSUE THREAD

**Issue by rennsax** [json-emacs/json-mode#80]
Behavior: when I turn on jsonc-mode, all hightlights suddenly disappear. And `what-cursor-position` shows no syntax faces.

Example:

jsonc-mode

![image](https://github.com/json-emacs/json-mode/assets/93167100/1b0ddbe3-eff8-4080-8582-c7e16eee8826)

json-mode

![image](https://github.com/json-emacs/json-mode/assets/93167100/8978b313-5e3d-4bca-82cd-614cc3c369d8)

**Comment by taku0** [comment]
Thank you for reporting a issue. What version of `json-mode` and Emacs do you use?

**Comment by rennsax** [comment]
I installed json-mode manually, so it's master.

**Comment by taku0** [comment]
I reproduced the bug in a fresh environment (but not my main environment). I will investigate it.

**Comment by taku0** [comment]
Fixed https://github.com/json-emacs/json-mode/commit/9a46569f81c048ce2b7b683cc0b3836f1c160b64.
